### ISSUE TITLE
多台机器多个adsl账号登录的问题

### ISSUE THREAD

**Issue by quantmod** [ysc/superword#3]
adsl拨号爬虫的问题：
假如我购买多个adsl账号，给每个linux服务器分配一个adsl账号，怎么部署呀？
多台机器请求同一个路由器登录adsl账号不是会冲突吗

**Comment by ysc** [comment]
一个adsl账号对应一根电话线和一个路由器，要是多个adsl账号那就需要多根电话线和路由器，一个[DynamicIp](https://github.com/ysc/superword/blob/master/src/main/java/org/apdplat/superword/tools/DynamicIp.java)进程对应一个路由器。

你可以不用购买adsl账号，使用[ProxyIp](https://github.com/ysc/superword/blob/master/src/main/java/org/apdplat/superword/tools/ProxyIp.java)的方式，如果免费的IP不够你用，你就买收费的IP。

**Comment by quantmod** [comment]
你那个getCurrentIp得到本机外网ip地址的url失效了 http://1111.ip138.com/ic.asp

**Comment by ysc** [comment]
http://1212.ip138.com/ic.asp
