### ISSUE TITLE
关于隐藏自己IP地址的代理

### ISSUE THREAD

**Issue by quantmod** [ysc/superword#4]
proxy_ips_excellent.txt
proxy_ips_normal.txt
proxy_ips.txt

不知道是不是程序bug，我实际运行过程中，proxy_ips_normal.txt中的有些ip我测试了一下是能够隐藏自己的IP，但是并没有被移到proxy_ips_excellent.txt文件中

**Comment by ysc** [comment]
应该不是BUG吧，可能你没测试对
